"""
DocumentAgent
=============
An agentic document-generation engine that crawls every source file in the
Dari project, sends each file to the local Ollama LLM for deep analysis, and
writes (or updates) rich Markdown documentation into backend/data/docs/.

Supported modes triggered by natural-language queries:
  - "document all"   → full re-scan and generation for every file
  - "update docs"    → regenerate docs only for files changed since last run
  - "document <path>"→ generate / refresh docs for a specific file
  - default          → list existing docs with summaries
"""

import os
import json
import asyncio
import hashlib
from pathlib import Path
from datetime import datetime
import httpx
from agents.base import BaseAgent
from agents.registry import registry
from loguru import logger

# ─────────────────────────────── constants ────────────────────────────────── #

OLLAMA_URL  = "http://localhost:11434/api/chat"
MODEL_NAME  = "gemma4:31b:cloud"

# Root of the entire Dari project (two levels above backend/)
PROJECT_ROOT = Path(__file__).resolve().parents[2]   # …/Dari/Dari
DOCS_DIR     = PROJECT_ROOT / "backend" / "data" / "docs"
HASH_FILE    = DOCS_DIR / ".file_hashes.json"        # tracks file checksums

# Files / dirs we do NOT want to document
SKIP_DIRS = {
    ".git", ".venv", "venv", "node_modules", "__pycache__",
    ".pytest_cache", "dist", "build", ".gemini", "data",
}
SKIP_FILES = {
    ".gitignore", "package-lock.json", ".file_hashes.json",
    "start_dari.py",          # bootstrap script
    "eslint.config.js",       # frontend tooling
    "vite.config.js",
    "index.html",             # web entry point
}

# Extensions we CAN document (source code + markdown only)
DOCUMENTABLE_EXTENSIONS = {
    ".py", ".js", ".jsx", ".ts", ".tsx",
    ".css", ".md",
}

# ───────────────────────────── LLM prompt ─────────────────────────────────── #

SYSTEM_PROMPT = """\
You are an expert software architect and technical writer.
Your job is to generate rich, developer-friendly Markdown documentation for a
single source file from the **Dari** project — an agentic AI-powered navigation
reasoning system.

For every file you receive, produce a Markdown document with **exactly** this
structure (keep the headings verbatim):

# <filename> — <one-line purpose>

## Overview
2-4 sentences describing what this file does and why it exists.

## Architecture Role
Where this file sits in the system (e.g., "Layer: Service", "Pattern: Strategy",
"Dependency direction: receives calls from X, calls Y").

## Key Concepts (Basics → Advanced)
Explain the most important ideas or patterns used, starting from fundamentals
and progressing to advanced details. Use sub-headings or numbered steps.

## Public API / Exports
A table or bullet list of every exported class, function, constant, or
component with a one-line description for each.

## Data Flow
Step-by-step description of how data enters, transforms, and leaves this file.
Use a numbered list or a simple ASCII diagram.

## Dependencies
List external libraries and internal modules it imports, with a short note on
why each is needed.

## Gotchas & Extension Points
Known limitations, edge cases, TODOs in the code, and recommended ways to
extend this file.

---
*Auto-generated by DocumentAgent on {date} using {model}.*

Rules:
- Use clean GitHub-Flavoured Markdown.
- Be precise: reference actual class names, function names, and variable names
  from the code.
- Do NOT wrap the output in code-fences. Return raw Markdown.
- Do NOT add any preamble outside the document structure above.
"""

ARCH_SYSTEM_PROMPT = """\
You are an expert software architect.
Given a JSON summary of every file in the **Dari** project, produce a
comprehensive **Architecture Overview** Markdown document with these sections:

# Dari — Architecture Overview

## Project Vision
What Dari is and what problems it solves.

## System Architecture Diagram
An ASCII block diagram showing all major layers and their relationships.

## Layer Breakdown
For each layer (Backend Core, Agent Layer, Service Layer, API Layer,
Frontend, Config & Tooling) explain its responsibilities.

## Request Lifecycle
Step-by-step trace of a typical user chat request through the entire system.

## Key Design Patterns
Patterns used (e.g., Strategy, Factory, Planner-Executor, RAG).

## Technology Decisions
Why each major technology was chosen (FastAPI, OSMnx, Ollama, React-Leaflet…).

## Future Roadmap
Improvements and extensions the architecture is designed to support.

---
*Auto-generated by DocumentAgent on {date} using {model}.*

Return raw Markdown only.
"""

# ─────────────────────────── helper utilities ─────────────────────────────── #

def _all_project_files() -> list[Path]:
    """Walk PROJECT_ROOT and return every documentable source file."""
    results = []
    for root, dirs, files in os.walk(PROJECT_ROOT):
        # Prune skipped directories in-place
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for fname in files:
            if fname in SKIP_FILES:
                continue
            fpath = Path(root) / fname
            if fpath.suffix in DOCUMENTABLE_EXTENSIONS:
                results.append(fpath)
    return sorted(results)


def _file_hash(path: Path) -> str:
    """MD5 checksum of a file — used to detect changes."""
    h = hashlib.md5()
    try:
        h.update(path.read_bytes())
    except Exception:
        pass
    return h.hexdigest()


def _load_hashes() -> dict:
    try:
        return json.loads(HASH_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _save_hashes(hashes: dict):
    HASH_FILE.write_text(json.dumps(hashes, indent=2), encoding="utf-8")


def _doc_path_for(source: Path) -> Path:
    """
    Map a source file → its documentation .md path inside DOCS_DIR.
    e.g. backend/agents/dari_agent.py → docs/backend/agents/dari_agent.py.md
    """
    rel = source.relative_to(PROJECT_ROOT)
    return DOCS_DIR / (str(rel).replace(os.sep, "/") + ".md")


def _read_source(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except Exception as exc:
        return f"[Could not read file: {exc}]"


# ──────────────────────────── LLM call ────────────────────────────────────── #

async def _call_llm(system: str, user: str, timeout: float = 120.0) -> str:
    """Send a prompt to Ollama and return the assistant text."""
    payload = {
        "model": MODEL_NAME,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user",   "content": user},
        ],
        "stream": False,
        "options": {"temperature": 0.2},
    }
    try:
        async with httpx.AsyncClient(timeout=timeout) as client:
            resp = await client.post(OLLAMA_URL, json=payload)
            resp.raise_for_status()
            return resp.json()["message"]["content"]
    except Exception as exc:
        logger.error(f"LLM call failed: {exc}")
        raise


async def _generate_file_doc(source: Path) -> str:
    """Ask the LLM to document a single source file."""
    code = _read_source(source)
    rel  = source.relative_to(PROJECT_ROOT)
    user_msg = (
        f"File path (relative to project root): `{rel}`\n\n"
        f"```{source.suffix.lstrip('.')}\n{code}\n```"
    )
    system = SYSTEM_PROMPT.format(
        date=datetime.now().strftime("%Y-%m-%d"),
        model=MODEL_NAME,
    )
    return await _call_llm(system, user_msg)


async def _generate_architecture_doc(file_summaries: dict[str, str]) -> str:
    """Ask the LLM to produce a system-wide architecture overview."""
    summary_json = json.dumps(
        {k: v[:300] + "…" for k, v in file_summaries.items()},  # truncate for context
        indent=2,
    )
    system = ARCH_SYSTEM_PROMPT.format(
        date=datetime.now().strftime("%Y-%m-%d"),
        model=MODEL_NAME,
    )
    user_msg = f"Here is a summary of every file in the project:\n\n{summary_json}"
    return await _call_llm(system, user_msg, timeout=180.0)


# ─────────────────────────── write helpers ────────────────────────────────── #

def _write_doc(doc_path: Path, content: str):
    doc_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.write_text(content, encoding="utf-8")
    logger.info(f"📄  Written → {doc_path.relative_to(PROJECT_ROOT)}")


def _build_index(hashes: dict) -> str:
    """Generate a master index of all documented files."""
    lines = [
        "# Dari — Documentation Index",
        "",
        f"> Auto-generated by DocumentAgent · {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "| File | Doc Link |",
        "|------|----------|",
    ]
    for rel_path in sorted(hashes.keys()):
        doc_link = rel_path + ".md"
        lines.append(f"| `{rel_path}` | [{doc_link}]({doc_link}) |")
    lines += ["", "---", "See `ARCHITECTURE.md` for the system-wide overview.", ""]
    return "\n".join(lines)


# ─────────────────────────────── agent ────────────────────────────────────── #

class DocumentAgent(BaseAgent):
    """
    Agentic documentation generator.

    On 'document all' or 'update docs' queries it:
      1. Walks every source file in the Dari project.
      2. Calls the Ollama LLM to produce per-file Markdown documentation.
      3. Writes each doc to backend/data/docs/<relative-path>.md
      4. Generates a project-wide ARCHITECTURE.md.
      5. Updates a master INDEX.md.
      6. Stores file hashes so future 'update' runs only re-process changed files.
    """

    def __init__(self):
        super().__init__(name="DocumentAgent")
        DOCS_DIR.mkdir(parents=True, exist_ok=True)
        registry.register("document", self)

    # ------------------------------------------------------------------ #
    async def execute(self, query: str) -> dict:
        q = query.lower().strip()

        if any(kw in q for kw in ("document all", "generate", "create doc", "update", "refresh")):
            return await self._run_full_generation(force_all="document all" in q or "create" in q)

        # "document <specific file path>"
        if q.startswith("document ") and len(q) > 9:
            target = query[9:].strip()
            return await self._document_single(target)

        # default — list existing docs
        return self._list_docs()

    # ------------------------------------------------------------------ #
    async def _run_full_generation(self, force_all: bool = False) -> dict:
        """Main pipeline: scan → LLM per file → write docs → architecture → index."""
        logger.info("DocumentAgent: starting full documentation generation…")
        hashes = _load_hashes()
        files  = _all_project_files()

        to_process = []
        for f in files:
            h = _file_hash(f)
            rel = str(f.relative_to(PROJECT_ROOT)).replace(os.sep, "/")
            if force_all or hashes.get(rel) != h:
                to_process.append(f)

        if not to_process:
            return {
                "type": "chat",
                "content": "✅ All documentation is already up-to-date! No files have changed.",
            }

        logger.info(f"DocumentAgent: {len(to_process)} file(s) to document.")
        summaries: dict[str, str] = {}
        errors: list[str] = []
        updated: list[str] = []

        for source in to_process:
            rel = str(source.relative_to(PROJECT_ROOT)).replace(os.sep, "/")
            logger.info(f"  Documenting: {rel}")
            try:
                content = await _generate_file_doc(source)
                doc_path = _doc_path_for(source)
                _write_doc(doc_path, content)

                # Store first 400 chars as summary for architecture pass
                summaries[rel] = content[:400]

                # Update hash
                hashes[rel] = _file_hash(source)
                updated.append(rel)
            except Exception as exc:
                logger.error(f"Failed to document {rel}: {exc}")
                errors.append(f"`{rel}` — {exc}")

        # ── Architecture overview ───────────────────────────────────────
        if summaries:
            logger.info("DocumentAgent: generating ARCHITECTURE.md…")
            try:
                arch_content = await _generate_architecture_doc(summaries)
                _write_doc(DOCS_DIR / "ARCHITECTURE.md", arch_content)
            except Exception as exc:
                logger.error(f"Architecture doc failed: {exc}")
                errors.append(f"ARCHITECTURE.md — {exc}")

        # ── Master index ────────────────────────────────────────────────
        _save_hashes(hashes)
        index_content = _build_index(hashes)
        _write_doc(DOCS_DIR / "INDEX.md", index_content)

        # ── Summary reply ───────────────────────────────────────────────
        parts = [
            f"✅ **Documentation complete!**",
            f"",
            f"📁 **Docs location:** `backend/data/docs/`",
            f"",
            f"**{len(updated)} file(s) documented:**",
        ]
        for u in updated:
            parts.append(f"  - `{u}`")
        if errors:
            parts += ["", "⚠️ **Errors:**"]
            parts += [f"  - {e}" for e in errors]
        parts += [
            "",
            "📐 **ARCHITECTURE.md** — system-wide overview generated.",
            "📋 **INDEX.md** — master documentation index updated.",
        ]

        return {"type": "chat", "content": "\n".join(parts)}

    # ------------------------------------------------------------------ #
    async def _document_single(self, target: str) -> dict:
        """Document one specific file by path fragment."""
        candidates = [
            f for f in _all_project_files()
            if target.replace("\\", "/") in str(f).replace("\\", "/")
        ]
        if not candidates:
            return {
                "type": "chat",
                "content": f"❌ Could not find a file matching `{target}` in the project.",
            }

        source = candidates[0]
        rel    = str(source.relative_to(PROJECT_ROOT)).replace(os.sep, "/")
        logger.info(f"DocumentAgent: single-file doc for {rel}")

        try:
            content  = await _generate_file_doc(source)
            doc_path = _doc_path_for(source)
            _write_doc(doc_path, content)

            hashes = _load_hashes()
            hashes[rel] = _file_hash(source)
            _save_hashes(hashes)

            return {
                "type": "chat",
                "content": (
                    f"✅ Documentation generated for `{rel}`.\n"
                    f"📄 Saved to `{doc_path.relative_to(PROJECT_ROOT)}`"
                ),
            }
        except Exception as exc:
            return {
                "type": "chat",
                "content": f"❌ Failed to document `{rel}`: {exc}",
            }

    # ------------------------------------------------------------------ #
    def _list_docs(self) -> dict:
        """Return a nicely formatted list of existing documentation files."""
        if not DOCS_DIR.exists():
            return {
                "type": "chat",
                "content": (
                    "📚 No documentation has been generated yet.\n\n"
                    "Say **\"document all\"** to scan every file and generate full docs using the AI!"
                ),
            }

        md_files = sorted(DOCS_DIR.rglob("*.md"))
        md_files = [f for f in md_files if f.name != ".file_hashes.json"]

        if not md_files:
            return {
                "type": "chat",
                "content": (
                    "📚 The docs folder exists but is empty.\n\n"
                    "Say **\"document all\"** to generate documentation for the entire codebase."
                ),
            }

        file_list = "\n".join(
            f"  - `{f.relative_to(DOCS_DIR)}`" for f in md_files
        )
        return {
            "type": "chat",
            "content": (
                f"📚 **{len(md_files)} documentation file(s)** in `backend/data/docs/`:\n\n"
                f"{file_list}\n\n"
                "Say **\"document all\"** to regenerate, or **\"update docs\"** to refresh only changed files."
            ),
        }
